- id: ryan_side_mini_1_pressed
  alias: Ryan Side Minimote Button 1 Pressed
  trigger:
  - event_data:
      entity_id: zwave.aeotec_dsa03202_minimote
      scene_id: 1
    event_type: zwave.scene_activated
    platform: event
  action:
  - data:
      entity_id: group.bedside_lights
    service: light.turn_on
- id: ryan_side_mini_2_pressed
  alias: Ryan Side Minimote Button 2 Pressed
  trigger:
  - event_data:
      entity_id: zwave.aeotec_dsa03202_minimote
      scene_id: 3
    event_type: zwave.scene_activated
    platform: event
  action:
  - data:
      entity_id: group.bedside_lights
    service: light.turn_off
- id: door_switch_on
  alias: Bedroom Door Switch Pressed
  trigger:
  - event_data:
      entity_id: zwave.battery_switch
    event_type: zwave.node_event
    platform: event
  action:
  - data:
      entity_id: group.bedroom_overhead
    service: light.toggle
- id: quadmote_1
  alias: Bedroom Light Toggle
  trigger:
  - event_data:
      entity_id: zwave.wallmote_1
      scene_id: 1
      scene_data: 0
    event_type: zwave.scene_activated
    platform: event
  action:
  - data:
      entity_id: light.bedroom_overhead_group
    service: light.toggle
- action:
  - data:
      entity_id: light.bedroom_overhead_group
      kelvin: 2500
      brightness: 255
    service: light.turn_on
  alias: Bedroom Warm
  condition: []
  id: '1532065044007'
  trigger:
  - event_data:
      scene_id: 2
      scene_data: 0
      entity_id: zwave.wallmote_1
    event_type: zwave.scene_activated
    platform: event
- id: quadmote_bright
  alias: Bedroom Wake-Up
  trigger:
  - event_data:
      scene_id: 4
      scene_data: 0
      entity_id: zwave.wallmote_1
    event_type: zwave.scene_activated
    platform: event   
  action:
  - data:
      entity_id: light.bedroom_overhead_group
      kelvin: 5200
      brightness: 255
    service: light.turn_on
