- id: ryan_side_mini_1_pressed
  alias: Ryan Side Minimote Button 1 Pressed
  trigger:
  - event_data:
      entity_id: zwave.aeotec_dsa03202_minimote
      scene_id: 1
    event_type: zwave.scene_activated
    platform: event
  action:
  - data:
      entity_id: group.bedside_lights
    service: light.turn_on
- id: ryan_side_mini_2_pressed
  alias: Ryan Side Minimote Button 2 Pressed
  trigger:
  - event_data:
      entity_id: zwave.aeotec_dsa03202_minimote
      scene_id: 3
    event_type: zwave.scene_activated
    platform: event
  action:
  - data:
      entity_id: group.bedside_lights
    service: light.turn_off
- id: door_switch_on
  alias: Bedroom Door Switch Pressed
  trigger:
  - event_data:
      entity_id: zwave.battery_switch
    event_type: zwave.node_event
    platform: event
  action:
  - data:
      entity_id: group.bedroom_overhead
    service: light.toggle
- id: quadmote_1
  alias: Bedroom Light Toggle
  trigger:
  - event_data:
      entity_id: zwave.wallmote_1
      scene_data: 0
      scene_id: 1
    event_type: zwave.scene_activated
    platform: event
  action:
  - data: {}
    entity_id: light.osram_lightify_a19_rgbw_00a4403c_3
    service: light.toggle
  - entity_id: light.osram_lightify_a19_tunable_white_0002484e_3
    service: light.toggle
- action:
  - data:
      entity_id: light.bedroom_overhead_group
      kelvin: 2500
      brightness: 255
    service: light.turn_on
  alias: Bedroom Warm
  condition: []
  id: '1532065044007'
  trigger:
  - event_data:
      scene_id: 2
      scene_data: 0
      entity_id: zwave.wallmote_1
    event_type: zwave.scene_activated
    platform: event
- id: quadmote_bright
  alias: Bedroom Wake-Up
  trigger:
  - event_data:
      entity_id: zwave.wallmote_1
      scene_data: 0
      scene_id: 4
    event_type: zwave.scene_activated
    platform: event
  action:
  - data:
      brightness: 255
      kelvin: 5200
    entity_id: light.osram_lightify_a19_rgbw_00a4403c_3
    service: light.turn_on
  - data:
      brightness: 255
      kelvin: 5200
    entity_id: light.osram_lightify_a19_tunable_white_0002484e_3
    service: light.turn_on
- id: '1561993739037'
  alias: Office Motion Detector Fires
  trigger:
  - entity_id: sensor.aeotec_zw100_multisensor_6_burglar
    for: 00:00:01
    from: '0'
    platform: state
    to: '8'
  condition: []
  action:
  - data:
      entity_id: input_boolean.office_occupied
    service: input_boolean.turn_on
- id: '1561993894388'
  alias: Office Motion Detector Clears
  trigger:
  - entity_id: sensor.aeotec_zw100_multisensor_6_burglar
    for: 00:00:01
    from: '8'
    platform: state
    to: '0'
  condition: []
  action:
  - data:
      entity_id: input_boolean.office_occupied
    service: input_boolean.turn_off
- id: '1561994146974'
  alias: Office Lights Up Dim
  trigger:
  - entity_id: input_boolean.office_occupied
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: light.office_wash_lights
    state: 'off'
  action:
  - data:
      brightness: 64
      entity_id: light.office_wash_lights
      transition: 5
    service: light.turn_on
- id: '1562075403262'
  alias: Office Lights Off
  trigger:
  - entity_id: input_boolean.office_occupied
    for: 0:05:00
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: light.office_wash_lights
    service: light.turn_off
